




---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: hw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hw
  template:
    metadata:
      labels:
        app: hw
    spec:
      containers:
      - name: hw
        image: hw
        ports:
          - containerPort: 80
        imagePullPolicy: Never
 


 
